@startuml
!include https://raw.githubusercontent.com/Intelliware/iwd-plantuml-styles/master/iwd_basic_styles.puml
!define TUPADR3 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.3.0
!includeurl TUPADR3/devicons/mysql.puml
!includeurl TUPADR3/devicons/php.puml
!includeurl TUPADR3/font-awesome/envelope.puml
!includeurl TUPADR3/font-awesome/mobile.puml
!includeurl TUPADR3/font-awesome/server.puml

title ==Zambia C4 Container Diagram

IwdRectangle("Users", "userGroup", "", "", "", "", "light") {

    IwdUser("Participant", "participant", "The participant updates their session interests, availability, and badge and publication information.")

    IwdIconOnly("Browser", "browser1", "", <img:https://github.com/Intelliware/iwd-plantuml-styles/raw/master/icons/browser.png> ,"A standard web browser is used to render the web app.")

    IwdIconOnly("Mobile App", "mobileApp", "", $mobile, "Mobile Apps for iPhone and Android can provide easy access to the schedule and con information")

    IwdUser("ConCom Staff", "concom", "The concom staff manages sessions, room assignments, participants on session and other session data. They can also run various reports.")

    IwdIconOnly("Browser", "browser2", "", <img:https://github.com/Intelliware/iwd-plantuml-styles/raw/master/icons/browser.png> ,"A standard web browser is used to render the web app.")
}

IwdRectangle("Registration System", "registration", "", "", "", "", "light") {

    IwdRectangle("Wellington", "wellington", "Ruby on Rails Application", $server, "The Wellington system provides a way for con attendees to register and pay for memberships", "System", "external") 

    IwdRectangle("Convention Master", "cm", "PHP Application", $server, "Convention Master is a commercial convention management system which handles not only con registration, but also has other features available in Zambia", "System", "external") 

    IwdRectangle("Balticon Online Reg", "balticon", "PHP Application", $server, "Balticon's Online Registration system is a very BaltiCon-specific registration system (which includes at-con registration and an admin system)", "System", "external") 
}

IwdRectangle("Zambia System", "zambiaContext", "", "", "", "", "exploded") {

IwdArtifact("Zambia", "zambia", "PHP Application", $php, "Zambia manages sessions and provides both participant and staff access to the system.", "System") 

IwdDatabase("Zambia Database", "db", "MySQL", $mysql, "The Zambia database stores data about participants, sessions, assignments, and other programming data.")

}

IwdRectangle("External Systems", "externalSystems", "", "", "", "", "light") {

    IwdRectangle("Email Server", "email", "SMTP Server", $envelope, "The email server provides standard SMTP access for password resets and notification about session assignments.", "System", "external") 
}

IwdArrow(participant, browser1, "uses", "", "right")
IwdArrow(participant, mobileApp, "uses", "", "right")
IwdArrow(browser1, mobileApp, "", "", "[hidden]down")
IwdArrow(mobileApp, browser2, "", "", "[hidden]down")
IwdArrow(browser1, zambia, "uses", "", "right")
IwdArrow(concom, browser2, "uses", "", "right")
IwdArrow(browser2, zambia, "uses", "", "right")
IwdArrow(mobileApp, zambia, "uses", "", "right")
IwdArrow(zambia, db, "reads/writes", "", "right")
IwdArrow(zambia, email, "invokes", "", "down")
IwdArrow(participant, concom, "", "", "[hidden]down")
IwdArrow(wellington, cm, "", "", "[hidden]down")
IwdArrow(cm, balticon, "", "", "[hidden]down")
IwdArrow(registration, zambiaContext, "feeds member data", "", "down")

@enduml
