<?php
//	Copyright (c) 2007-2021 Peter Olszowka. All rights reserved. See copyright document for more details.
//	RenderPrecis display requires:  a query result containing rows with these fields IN THIS ORDER:
//	$sessionid, $trackname, $typename, $title, $duration, $estatten, $progguiddesc, $persppartinfo, $starttime, $roomname, $statusname
//	it displays the precis view of the data.
function RenderPrecis($result, $showlinks, $href, $sessionSearchArray) {
    $html = RenderPrecisToString($result, $showlinks, $href, $sessionSearchArray);
    echo $html;
}

function RenderPrecisToString($result, $showlinks, $href, $sessionSearchArray) {
    $html = "";

    $html .= "<div class=\"alert alert-info mt-3\">Generated by Zambia: " . date('d-M-Y h:i A') . "</div>\n";
    if (mysqli_num_rows($result) < 1) {
        $html .=  "<p class=\"alert alert-warning\">No matching results found.</p>";
        return $html;
    }
    $html .=  "<div class=\"card\"><div class=\"card-body\">";
    if ($href) {
        $params = "";
        foreach ($sessionSearchArray as $key => $value) {
            if ($value && $value !== "") {
               $params .= ("&$key=" .urlencode($value));
            }
        }

        $html .=  "<div class=\"text-right\"><a class=\"btn btn-secondary btn-sm\" href=\"$href?csv=csv$params\">Download CSV</a></div>";
    }
    $html .=  "<p>If a room name and time are listed, then the session is on the schedule; otherwise, not.</p>";
    $html .=  "<table class=\"table table-sm\">\n";
    while (list($sessionid, $trackname, $typename, $title, $duration, $estatten, $progguiddesc, $persppartinfo, $starttime, $roomname, $statusname, $taglist)
        = mysqli_fetch_array($result, MYSQLI_NUM)) {
        $html .= "<tr>\n";
        $html .= "  <th rowspan=\"3\" id=\"sessidtcell\">";
        if ($showlinks) {
            $html .= "<a href=\"StaffAssignParticipants.php?selsess=" . $sessionid . "\">" . $sessionid . "</a>";
        } else {
            $html .= "$sessionid";
        }
        $html .= "</th>\n";
        if (TRACK_TAG_USAGE !== "TAG_ONLY") {
            $html .= "  <td>" . $trackname . "</td>\n";
            $html .= "  <td>" . $typename . "</td>\n";
        } else {
            $html .= "  <td colspan=\"2\">" . $typename . "</td>\n";
        }
        $html .= "  <td style=\"font-weight:bold\">";
        if ($showlinks) {
            $html .= "<a href=\"EditSession.php?id=" . $sessionid . "\">" . htmlspecialchars($title, ENT_NOQUOTES) . "</a>";
        } else {
            $html .= htmlspecialchars($title, ENT_NOQUOTES);
        }
        $html .= "&nbsp;&nbsp;</td>\n";
        $html .= "  <td>" . $duration . "</td>\n";
        $html .= "  <td>";
        if ($roomname) {
            $html .= $roomname;
        } else {
            $html .= "&nbsp;";
        }
        $html .= "</td>\n";
        $html .= "  <td>";
        if ($starttime) {
            $html .= $starttime;
        } else {
            $html .= "&nbsp;";
        }
        $html .= "</td>\n";
        $html .= "    <td>$statusname</td>\n";
        if ($showlinks) {
            $html .= "    <td><a class=\"btn btn-sm btn-outline-secondary\" href=\"SessionHistory.php?selsess=$sessionid\">History</a></td>\n";
        } else {
            $html .= "<td></td>";
        }
        $html .= "</tr>\n";
        $html .= "<tr>";
        $html .= "    <td colspan=\"2\">" . htmlspecialchars($taglist, ENT_NOQUOTES) . "</td>";
        $html .= "    <td colspan=\"6\">" . htmlspecialchars($progguiddesc, ENT_NOQUOTES) . "</td>";
        $html .= "</tr>\n";
        if ($persppartinfo) {
            $html .= "<tr><td></td>";
            $html .= "<td colspan=\"2\">Prospective Participant Info: </td>";
            $html .= "<td colspan=\"6\">".htmlspecialchars($persppartinfo,ENT_NOQUOTES)."</td>";
            $html .= "</tr>\n";
        } else {
            $html .= "<tr><td colspan=\"8\">&nbsp;</td></tr>\n";
        }
    }
    $html .= "</table>\n";
    $html .= "</div></div>";
    return $html;
}
?>
